
# 数据库配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # thymelea 视图模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
#thymeleaf end

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.modules



# 日志配置文件
#logging:
#  config: classpath:logback-spring.xml1

# 内嵌 tomcat 端口
server:
  port: 8081
